### ISSUE TITLE
ability to set exchange type for AMQP adapter

### ISSUE THREAD

**Issue by miladazhdehnialcads** [moleculerjs/moleculer-channels#35]
Hi, thanks for this nice library.
Is there a reason that the type of exchange can not be changed as an option?

https://github.com/moleculerjs/moleculer-channels/blob/024c251a69c1a850721ca0aac556c880bbfc6960/src/adapters/amqp.js#L289

**Comment by icebob** [comment]
Because the `fanout` can cover the logic that is implemented in this library.
