### ISSUE TITLE
move channel to root of config's object?

### ISSUE THREAD

**Issue by 0x0a0d** [moleculerjs/moleculer-channels#36]
I think channel can be defined in `moleculer.config.js` likes this
```js
module.export = {
// ...
channel: {
  redis: {
    // config
  },
//  more : {},
},
//...
}
```

because current way to use channel middleware, made it can not
> overwrite broker’s deeply nested default options, which are not present in moleculer.config.js, via environment variables
https://moleculer.services/docs/0.14/runner.html#Configuration-loading-logic

**Comment by icebob** [comment]
I don't agree with it. The moleculer-channel is a middleware, and `moleculer.config` contains settings for ServiceBroker and internal modules only.

You can use env vars this way:
```js
module.exports = {
    logger: true,

    middlewares: [
        ChannelsMiddleware({
            adapter: process.env.CHANNELS_ADAPTER_URL
        })
    ]
};
```
