### ISSUE TITLE
Error on reconnection with resubscribeAllChannels

### ISSUE THREAD

**Issue by DavidP-B** [moleculerjs/moleculer-channels#40]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

## Current Behavior

When I'm running moleculer-channels and I got an error, timeout o whatever (an error how cause a reconnection to amqp) when moleculer-channels try to reconnects calls method **resubscribeAllChannels**. This method always return an error **Already tracking active messages of channel XXXX** which is located in the method **initChannelActiveMessages**.

## Expected Behavior

No errors and reconnectins as usual.

## Temporal solution
I put a try/catch inside **resubscribeAllChannels**

```js
async resubscribeAllChannels() {
		this.logger.info("Resubscribing to all channels...");
		for (const { chan } of Array.from(this.subscriptions.values())) {
			try {
				await this.subscribe(chan);
			} catch (e) {
				this.logger.error('[resubscribeAllChannels]', e)
			}
		}
	}
```

## Question
Is necessary call the method **resubscribeAllChannels**, because I make some tests commenting this line and all works well.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.17
* NodeJS version: 12.22.6

**Comment by DavidP-B** [comment]
Also I don't undestand this part. ConnectionCount is used to know if there is a reconnection, but always will be reconnect because after the channel created, you sum 1 to connection count, so isReconnect always return true.

`this.logger.info("AMQP channel created.");
		this.connectionCount++;

		const isReconnect = this.connectionCount > 1;
		if (isReconnect) {
			await this.resubscribeAllChannels();
		}`

**Comment by icebob** [comment]
>Also I don't undestand this part. ConnectionCount is used to know if there is a reconnection, but always will be reconnect because after the channel created, you sum 1 to connection count, so isReconnect always return true.
The `connectionCount` initialized to 0, so first time it will be false (1 > 1 == false).

Could you write repro steps and env?
