### ISSUE TITLE
Redis Cluster Configuration Issue

### ISSUE THREAD

**Issue by valeeum** [moleculerjs/moleculer-channels#43]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

I'm currently running a Redis cluster and noticed that defining the "cluster" parameter at the top level per the Readme was not connecting successfully.    After looking at the source code, I noticed that the "cluster" property needs to be defined under the "redis" property. 

## Expected Behavior

Cluster configuration per instructions in Readme should result in successful connection to cluster. 

### Reproduce code snippet
This does NOT work: 
```js
ChannelsMiddleware({
        adapter: {
          type: "Redis",
          options: {
            cluster: { nodes: [ ... ]},
            redis: {
              consumerOptions: { .... }
          }
    }
}
```

This DOES works: 
```js
ChannelsMiddleware({
        adapter: {
          type: "Redis",
          options: {
            redis: {
              cluster: { nodes: [ ... ]},
              consumerOptions: { .... }
          }
    }
}
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.23
* NodeJS version: 14
* Operating System: OSX

### Failure Logs
N/A

**Comment by icebob** [comment]
Good catch, thanks!
