### ISSUE TITLE
sendToChannel middleware hook is not firing

### ISSUE THREAD

**Issue by ujwal-setlur** [moleculerjs/moleculer-channels#65]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed
- [X ] I'm reporting the issue to the correct repository

## Current Behavior

I have a middleware where I have both ```localChannel``` and ```sesndToChannel``` hooks. The ```localChannel``` hook is firing, but the ```sendToChannel``` hook is not.
## Expected Behavior

```sendToChannelHook``` should fire.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Create middleware with ```localChannel``` and ```sendToChannel``` hooks. The middleware is dynamically loaded after broker starts with ```broker.middlewares.add()```

### Reproduce code snippet

```js
    localChannel(next, chan) {
        return async (msg, raw) => {
            this.logger.info(kleur.magenta(`  Before localChannel for '${chan.name}'`), msg);
            await next(msg, raw);
            this.logger.info(kleur.magenta(`  After localChannel for '${chan.name}'`), msg);
        };
    },

    // Wrap the `broker.sendToChannel` method
    sendToChannel(next) {
        return async (channelName, payload, opts) => {
            this.logger.info(kleur.yellow(`Before sendToChannel for '${channelName}'`), payload);
            await next(channelName, payload, opts);
            this.logger.info(kleur.yellow(`After sendToChannel for '${channelName}'`), payload);
        };
    }
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.29
* NodeJS version: 18.13.0
* Operating System: OS X Ventura

### Failure Logs
none

**Comment by AndreMaz** [comment]
Hi @ujwal-setlur This is also related to the previous issue that you've opened re dynamic middleware. Please check this comment: https://github.com/moleculerjs/moleculer-channels/issues/60#issuecomment-1412498489
