### ISSUE TITLE
Redis Adapter Capped Stream Support -  "MAXLEN ~"

### ISSUE THREAD

**Issue by valeeum** [moleculerjs/moleculer-channels#69]
Would be nice to be able to support creating capped streams using `MAXLEN ~` when calling clientPub.xaddBuffer(...args) method.  

https://redis.io/docs/data-types/streams-tutorial/#capped-streams

**Comment by icebob** [comment]
I've added it. https://github.com/moleculerjs/moleculer-channels/pull/70

Please try it before merging. I've tried but I don't experience any changes on Redis side

To try, install as `npm i moleculerjs/moleculer-channels#xaddMaxLen`

**Comment by valeeum** [comment]
sorry for the delayed response but it seems like it's working great.

**Comment by valeeum** [comment]
i pushed the code into a forgiving production workload so i will report back if i encounter any issues.

**Comment by valeeum** [comment]
@icebob everything is working as expected and can be merged into the master branch.  thank you for this update!
