### ISSUE TITLE
Redis adapter

### ISSUE THREAD

**Issue by putty-kang** [moleculerjs/moleculer-channels#74]
Publish offline messages, simulate subscription exceptions, set to retry 100 times, and disconnect the subscription end when sending 10 times,
When the subscriber reconnects, the subsequent retry message cannot be received and the message is lost

**Comment by icebob** [comment]
Please create a reproduction code.

**Comment by putty-kang** [comment]
// static-service.js
const { ServiceBroker } = require("moleculer");
const ChannelsMiddleware = require("@moleculer/channels").Middleware;
const broker = new ServiceBroker({
  namespace: "test",
  nodeID: "test1",
  transporter: "TCP",
  middlewares:[ChannelsMiddleware({
    adapter:"redis://127.0.0.1:6379"
  })]
});

// Start the Moleculer broker
broker.start();

broker.repl();

setInterval(() => {
  broker.sendToChannel("order.created", {
    id: 1234,
    items: "test"
  });
}, 100);


// Start the service to serve static resources

const serviceSchema = {
  name: "subscriber",
  channels: {
    "order.created": {
      group: "mygroup",
      redis: {
        minIdleTime: 1000,
        claimInterval: 1,
        startID: "0"
      },
      maxRetries: 100,
      handler(payload) {
          console.log(payload);
          throw new Error;
      }
    }
  },
}
broker.createService(serviceSchema).then();

// send 10 times

broker.destroyService("subscriber").then(()=>{
  setTimeout(()=>{
    // then create new Service, Remaining transmission times data loss

broker.createService(serviceSchema);
  }, 10000);
});

**Comment by putty-kang** [comment]
How to ensure that data in pending is not lost after destroying the service

**Comment by valeeum** [comment]
@putty-kang 
The default value for moleculer channels configuration for redis.startID is "$" which means pick up only new messages.  You will need to store and manage this value if you want to pick up messages that may have come in while service was down.

_Starting point when consumers fetch data from the consumer group. By default equals to $, i.e., consumers will only see new elements arriving in the stream. More info [here](https://redis.io/commands/XGROUP)_

**Comment by putty-kang** [comment]
@icebob
                                            const pubClient = this.clients.get(this.pubName);
										// 1. Delete consumer from the consumer group
										// 2. Do NOT destroy the consumer group
										// https://redis.io/commands/XGROUP
										return pubClient.xgroup(
											"DELCONSUMER",
											chan.name, // Stream Name
											chan.group, // Consumer Group
											chan.id // Consumer ID
										);

================================================================================

This code results in the loss of unconsumed messages in the reconnecting extension after the service is disconnected

**Comment by putty-kang** [comment]
@icebob

You need to first check if there is a message in the ending, and then delete the corresponding consumer

**Comment by putty-kang** [comment]
const pubClient = this.clients.get(this.pubName);
										let pending = await pubClient.xpending(
											chan.name,
											chan.group,
											"-",
											"+",
											10 // Max reported entries
										);
										if(!pending) {
											// 1. Delete consumer from the consumer group
											// 2. Do NOT destroy the consumer group
											// https://redis.io/commands/XGROUP
											return pubClient.xgroup(
												"DELCONSUMER",
												chan.name, // Stream Name
												chan.group, // Consumer Group
												chan.id // Consumer ID
											);
										}

**Comment by AndreMaz** [comment]
Repro example and the proposed fix are here: https://github.com/moleculerjs/moleculer-channels/commit/8c3eb6e5c64cad27d75e5479f38c7a97b4e18cd4
